### ISSUE TITLE
Enhancement: Presets, w/ Visual Representation of Transformation

### ISSUE THREAD

**Issue by djpretzel** [carrierdown/mutateful#13]
- Love this concept
- But I'm very lazy.... and so are many others
- The documentation has plenty of cool examples of transformations
- How about a dropdown w/ presets that also shows a visual before/after of the the preset transformation?

**Comment by carrierdown** [comment]
This is planned. However, it is a major undertaking, so do not expect it in the near future. I'll post a roadmap in the project readme soon, which will give a bit more info about what needs to be in place before this can happen.

**Comment by carrierdown** [comment]
Added a roadmap on the wiki where this is [described](https://github.com/carrierdown/mutateful/wiki/Roadmap).
