### ISSUE TITLE
You can’t use this version of the application “Mutateful” with this version of OS X. (10.11.6)

### ISSUE THREAD

**Issue by DystopianDisco** [carrierdown/mutateful#15]
You have OS X 10.11.6. The application requires OS X 10.13 or later. Can't update environment/OS. Anyway around this?

**Comment by carrierdown** [comment]
The .NET Core 3 runtime imposes this restriction I'm afraid. I suppose it would be possible to retarget it to run on the Mono runtime instead, which I think would make it compatible with older OS versions as well. If anyone is willing to help out getting this done then feel free!

**Comment by twobob** [comment]
Relevant Addendum, Windows 10 rev. 1079 minimum is also a restriction placed by Core 3 to build on VS 2019 (Which seems reasonable since that is the revision they introduced the core changes).
