### ISSUE TITLE
=d1 arp -by c1 -by b1 needs catching in parser

### ISSUE THREAD

**Issue by twobob** [carrierdown/mutateful#16]
> Welcome to mutateful!
> Open Ableton Live, drop mutateful-connector.amxd onto one of the tracks, and start entering formulas.
> watchedclips at 2557 set to 2524
> Received 2 clips and formula: **[<d1>0] arp -by [<b1>1]**
> Sent 309 bytes over UDP
> Received 1 clips and formula: **[<d1>0] relength 2.0**
> Sent 159 bytes over UDP
> watchedclips at 2556 set to 2524
> Received 3 clips and formula: **[<d1>0] arp -by [<c1>1] -by [<b1>2]**
> Unhandled exception. System.ArgumentException: An item with the same key has already been added. Key: By
>    at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
>    at Mutate4l.Cli.Parser.ParseTokensToCommand(IEnumerable`1 tokens)
>    at Mutate4l.Cli.Parser.<>c.<ParseFormulaToChainedCommand>b__1_3(List`1 x)
>    at System.Linq.Enumerable.SelectListIterator`2.ToList()
>    at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
>    at Mutate4l.Cli.Parser.ParseFormulaToChainedCommand(String formula, List`1 clips, ClipMetaData metadata)
>    at Mutate4l.Cli.CliHandler.Start()
>    at Mutate4l.Program.Main(String[] args)
> 
> 

Edge case maybe but there

**Comment by carrierdown** [comment]
Agree that the parser should handle that.
