### ISSUE TITLE
"Relength" Relen and RL

### ISSUE THREAD

**Issue by twobob** [carrierdown/mutateful#23]
In practical use commands that don't have a TLA (Two/three letter acronym in this case) are cumbersome.  Going forward if all command could have a TLA that would be ideal.
(With exception to things that possibly have no good shortname like "scan")

For those cases that are currently missing a TLA obviously considerations such as 'clarity of short-name'; 'avoiding accidental cognates' and of course the general lack of namespace are key.

Recognising that would it be better to just provide a push with my ideas or do you want to hash it out in comments on this issue first?

Many thanks.

**Comment by twobob** [comment]
{ "relength", Relength }, { "relen", Relength }, { "rl", Relength },
for example

**Comment by twobob** [comment]
I also note that the order of "nicknames" is not 'fixed' in the code
            { "il", Interleave }, { "interleave", Interleave },
            { "ilev", InterleaveEvent }, { "interleaveevent", InterleaveEvent },
Break the convention. 
Could make that a "thing" and tidy it up during my push.

**Comment by carrierdown** [comment]
Thanks, feel free to submit a PR for this :) I think 4-letter commands could make do without further shortening, but 3-4 letters is a good fit I think.

**Comment by twobob** [comment]
Willdo. are one letter abbreviations okay for special cases like MidiVelocity where "v" really makes the most sense and you type it all the time. I'll consider the justification anyway on this side and see what makes the most sense in use for now.  Obviously it has a chance of misunderstanding the users part and also perhaps being a typo; but typing v.9 was very freeing :)

**Comment by carrierdown** [comment]
Feel free to experiment a bit here and we'll see what sticks. Using v is probably ok for the velocity/velo command :)

**Comment by twobob** [comment]
Handled in Pull #35
