### ISSUE TITLE
VelocityScale

### ISSUE THREAD

**Issue by twobob** [carrierdown/mutateful#24]
I've been using the following to scale my velocities.
I recognise it could have more options but it's what I currently use.

Would this be useful upstream?
https://gist.github.com/twobob/c6355773901d7517b0d0dc7249085f73

It just floors the multiplicative to int per note with some scaffolding
Thanks

**Comment by twobob** [comment]
I'll ask again when it's ready

**Comment by twobob** [comment]
Well I might as well ask anyway. Something like this useful?

**Comment by carrierdown** [comment]
That seems useful, yeah. Submit a PR and I'll have a look at it when time allows :)

**Comment by twobob** [comment]
Thanks

**Comment by twobob** [comment]
Handled in pull #35
