### ISSUE TITLE
Port _ x * ' and : operators from re<urse

### ISSUE THREAD

**Issue by carrierdown** [carrierdown/mutateful#30]
These operators would be very useful to have in mutateful as well.

Examples: 

- 1x5 becomes 1 1 1 1 1
- Ranged values like 1:5 (start at 1, interpolate towards 5 for the length of the clip), or 1:5:1 (start at one, end at 5, increment by 1 for each step, possibly wrapping back to 1 if the clip is long enough)
- Silence, discardable values: _
- Fill operator: *
- Alternation operator: ' (e.g. 1 2'3'4 1 becomes 1 2 1 1 3 1 1 4 1 ... and so on)

**Comment by carrierdown** [comment]
Implementing operators that require interpolation across the generated sequence is outside the scope of this feature. For this to work, we would need to implement something like what's described (and implemented) here: https://github.com/carrierdown/recurse/blob/d6cc70270fd69be9a887d33a5aefc6748ec39590/recurse-app/app/src/function/generator/RhythmicMotive.ts#L52

**Comment by twobob** [comment]
Noted. Coupled with the tenuously mooted "add option to constrain to pitch based on position, so that events occuring for instance during a chord are constrained to this only. " in Scale this could be a super powerful way to generate long phase cross-cadence lead lines :)

**Comment by twobob** [comment]
Just reffing   67446d7 for the repeat operator for future deep divers.

**Comment by carrierdown** [comment]
Fixed most of the stuff discussed here in 0cca9a1c90f39627021a4f60bd40f765650bd480
