### ISSUE TITLE
Component Path Issue

### ISSUE THREAD

**Issue by ClayLimb** [carrierdown/mutateful#33]
Having a bit of trouble running the UNIX exec application on macOS Mojave 10.14.5 despite it working perfectly before. Receiving the following issue with both the v1.0.1 and v1.0 builds upon opening:

The application to execute does not exist: '/private/var/folders/6x/x59ln4fd5y1dvdz7zlxm5rph0000gn/T/.net/Mutate4l/cgscinom.sti/Mutate4l.dll'.

Seems to be looking for a .dll library file but the path goes bad after [/T/], and I can't seem to find anything helpful in the code or patchers for either version. Any help would be appreciated, excited to work with the new commands!

**Comment by carrierdown** [comment]
Hmm, I haven't encountered issues like this before, but it seems to be a .NET Core issue really. What I'd recommend is to try and compile the app yourself. It's quite straight forward to do and building from master also gets you the latest commands to play with.

There's a description at the bottom of the project readme, let me know if you need more guidance on this.

**Comment by ClayLimb** [comment]
Compiling from the master build in terminal solved it! Thanks!
