### ISSUE TITLE
Common Time maths, Clip denominators and numerators, 

### ISSUE THREAD

**Issue by twobob** [carrierdown/mutateful#34]
Whilst doing some very basic tests I noted that all internal maths is performed with an assumption of 4/4 and clips that are copied in non common-time signatures via concat end up being 4/4 (and obviously the wrong length)

It may not be well known that one can name the scenes with a Signature and BPM and the transport auto-switches to it on playback. (Shown in diagram)

This being the case supporting multi time playback seems more critical.
Noted that Clip class did not have a concept of signature_numerator and signature_denominator properties and moreover I suppose this also need generalising to not mash up any other extant math wangles you did for establishing timings and whatnot.  Thus I did not look at what it would take to support this end to end yet as you would very likely know the gotchas.  But seemed worthy of note here.  Seems to me that any  extant maths would just need scaling by the reciprocal of the results from "factor of  signature_numerator over signature_denominator" for both such that 3/4 from 4/4 gives us 1.33333333333 but maybe I am wrong there. 

![image](https://user-images.githubusercontent.com/915232/69663693-a77afb80-107e-11ea-8164-1de0306f5a2c.png)

In the interim common-time is the only safe choice

**Comment by twobob** [comment]
Not sure if this is "Support signature_numerator and signature_denominator"  or "Support little known scene naming wangles"  or both?  But anyway.

**Comment by carrierdown** [comment]
Thanks for reporting. However, as far as I can tell, this is a problem with Ableton Live itself. If you create some clips that are, for instance 3/4, mutateful will handle these correctly as long as the clip lengths are set properly. However, if you have a clip that was originally 4/4 and you change it to be 3/4, Live won't change the length of the clip, resulting in broken output.

Additionally, if you change the global time signature, there is no way for mutateful to know this, since it operates at the clip level.

If you have any ideas on how this could be handled differently, I'm open for suggestions.

**Comment by twobob** [comment]
The "scene name" thing is perhaps helpful here then.  The solution seems workflow related in that case:  If one ensures that the names of the two scenes contains the right time signature (say both 3/4) then upon creation of a clip in that scene Ableton will default to creating clips of the correct signature (rather than the global signature which is used in cases where the scene name is absent).

I concur it is a very odd OOTB operation.  Non-issue maybe?  not sure.
As for

**Comment by carrierdown** [comment]
That might be a possibility, yeah. Also, mutateful should probably respect the time signature of new clips it creates based on the signature of the clips passed in. However, they may not always match up, so it's less clear what should be done in this cases.

**Comment by twobob** [comment]
I totally agree. in the end the maths is just scaling by the reciprocal of the results from "factor of signature_numerator over signature_denominator" for both to get back to the original lengths but it's how meaningful that data would end up being. it feels like "stretching" the data to fit is the right choice here, but really not sure.
