### ISSUE TITLE
Getting this error in terminal "The application to execute does not exist"

### ISSUE THREAD

**Issue by piearesquared** [carrierdown/mutateful#37]
Everything was working fine until today, when it started giving me this error:
exit;
The application to execute does not exist: '/private/var/folders/r9/zm8jfd9112l0w8r9xl56ycz00000gn/T/.net/Mutateful/iwn3ozxb.2zu/Mutate4l.dll'.
I am on High Sierra 10.13.5
Tried to download and relaunch but keep getting this, any ideas to what I might've done to cause it to do this? 
Thanks

**Comment by carrierdown** [comment]
Have a look at issue #33.
