### ISSUE TITLE
macOS errors loading UDP externals

### ISSUE THREAD

**Issue by rf-** [carrierdown/mutateful#40]
Hi, I just started from scratch with the 1.1 release on Catalina 10.15.5. Populating the formula ids works correctly, but the formulas themselves don't do anything, and when I edit the device I see some errors in the Max console:

<img width="416" alt="image" src="https://user-images.githubusercontent.com/345106/86523108-586b2500-be1c-11ea-9682-45b3b1b652aa.png">

I just had the experience setting up [gibberwocky](https://github.com/gibber-cc/gibberwocky) of needing to use `xattr` to remove a quarantine attribute from externals before Max could load them, so it occurred to me that the problem here could be similar, but I actually have no idea where the `sadam.udp*` externals are (supposed to be) stored.

**Comment by rf-** [comment]
OK, I was able to get it working. First I downloaded the repo and put the externals in `~/Documents/Max 8/Library`. Once I'd done that, I started getting these errors instead:

<img width="417" alt="image" src="https://user-images.githubusercontent.com/345106/86523164-2b6b4200-be1d-11ea-92f7-fe4162d2de82.png">

At this point, running `sudo xattr -d -r com.apple.quarantine .` in `Library` cleared up the remaining errors, and it works now. I'm not sure what the path forward is for making it work out of the box, but hope this helps.

**Comment by carrierdown** [comment]
Glad to hear you got it working! And thanks for documenting your approach for getting it working, that will probably be useful for others as well 👍

**Comment by carrierdown** [comment]
A lot of these problems would probably go away if we could get away with just using built in Max objects. However, the built in Max objects unfortunately don't support sending binary data, so I would have to resort to some kind of text encoding scheme like base64, which would be bad for bandwidth. This is particularly true for UDP communication which has small package sizes to begin with.
