### ISSUE TITLE
Live 11?

### ISSUE THREAD

**Issue by beep-beep-beep-boop** [carrierdown/mutateful#43]
Not sure if this issue is bc I'm using live 11 or if its another bug but there are no errors in the mutateful application or the m4l device but no formulas work. the automatic setting of clip names works but formulas dont create any notes.

**Comment by ashNotKetchup** [comment]
Is this still the case?

> The current release version of mutateful is not compatible with L11 I'm afraid. I have the code ready for L11 support on `master`, but I'm also in the midst of a complete rewrite of mutateful itself (including how communication with Live is handled), so at the moment there is no stable version available.

**Comment by carrierdown** [comment]
No, the current master branch is compatible with Live 11. Just haven't gotten around to releasing it yet. I'll release a beta shortly.

**Comment by carrierdown** [comment]
I've just released a beta of Mutateful 1.5 which supports Live 11. You can find it here:  https://github.com/carrierdown/mutateful/releases/tag/v1.5-beta1
