### ISSUE TITLE
Enhancement: Insert silence

### ISSUE THREAD

**Issue by twobob** [carrierdown/mutateful#6]
It would be helpful to pad silence 

perhaps 
padtime [-at time] [duration] 

and just insert that as blank space
Many thanks, Even just at the start would be fine. 

This is particularly relevant for things like SCAN where the results can be hard to envisage in advance and hard to sync in retrospect.

Not least it can be used for rhythm nudging.  At which point a negative value might be handy to delete time at the start too.

**Comment by carrierdown** [comment]
I'll think about it. This might also be something you could add yourself if you want a somewhat bigger challenge after tackling #5

**Comment by twobob** [comment]
Seems like I would take the extant notes and shift them by -duration possibly with an -inverse.
This would preclude operating on blank clips one supposes and poses challenges of what to do with stuff that rolls off the ends.  Does that cover it for you in terms of challenges?

**Comment by carrierdown** [comment]
Sounds about right. The clip length needs to be updated to avoid events outside the bounds of the clip. I think deleting stuff at the start would not be needed here, and would be better covered by a separate command called trim or something like that. Removing stuff from the beginning of the clip is already handled by the Take command.

**Comment by twobob** [comment]
Righto - I'll look at that later

**Comment by twobob** [comment]
I asked #9 to get a sense of the complete picture.

**Comment by carrierdown** [comment]
@twobob Are you still up for this one?

**Comment by twobob** [comment]
I am - I was waiting for the timing thing to come in.
Apologies, moved 8 tons of Rocks and Soil in the last week.

**Comment by carrierdown** [comment]
No worries, everything in its own time :) You seem to have a diverse range of tasks to work on at least :D

**Comment by twobob** [comment]
> 
> 
> Sounds about right. The clip length needs to be updated to avoid events outside the bounds of the clip. I think deleting stuff at the start would not be needed here, and would be better covered by a separate command called trim or something like that. Removing stuff from the beginning of the clip is already handled by the Take command.

I'm not entirely sure if _"The clip length needs to be updated to avoid events outside the bounds of the clip."_ is actually the case, having played around now, being able to half push the notes over the looped end is actually pretty cool.   Scaffolding to exclude such notes could be added but not certain it's required.

Yes, deletion of data is not part of this for sure, crop and take are better suited for their specific tasks.

ref https://github.com/carrierdown/mutateful/pull/22

**Comment by carrierdown** [comment]
Closing this as Padding has been merged into master now
